lines.append('#!/usr/bin/env python3')
lines.append('"""MoA Vision Agent — 微信小弟的看图能力"""')
lines.append('import os, sys, json, time')
lines.append('from pathlib import Path')
lines.append('')
lines.append('sys.path.insert(0, str(Path.home() / ".openclaw" / "workspace" / "moa"))')
lines.append('from vision import describe_image, check_model_ready, model_status, load_vision_model')
lines.append('')
lines.append('def handle_image(image_path, query=""):')
lines.append('    if not os.path.exists(image_path):')
lines.append('        return "图片文件不存在: " + image_path')
lines.append('    if not check_model_ready():')
lines.append('        s = json.dumps(model_status(), ensure_ascii=False)')
lines.append('        return "视觉模型还在下载中，请稍后再试\\n当前状态: " + s')
lines.append('    if query and len(query) > 2:')
lines.append('        prompt = "请回答关于这张图片的问题：" + query')
lines.append('    else:')
lines.append('        prompt = "请详细描述这张图片中的内容，包括物体、颜色、文字、场景等"')
lines.append('    try:')
lines.append('        return describe_image(image_path, prompt)')
lines.append('    except Exception as e:')
lines.append('        return "[Vision Error] " + str(e)')
lines.append('')
lines.append('def main():')
lines.append('    print("=" * 60)')
lines.append('    print("  MoA Vision Agent")')
lines.append('    print("=" * 60)')
lines.append('    status = model_status()')
lines.append('    print("  视觉模型状态:", status["status"])')
lines.append('    if status["status"] == "ready":')
lines.append('        print("  模型大小:", status.get("size_mb", "?"), "MB")')
lines.append('        try:')
lines.append('            load_vision_model()')
lines.append('            print("  测试通过 OK")')
lines.append('        except Exception as e:')
lines.append('            print("  测试失败:", e)')
lines.append('    elif status["status"] == "downloading":')
lines.append('        print("  正在下载中...")')
lines.append('    else:')
lines.append('        print("  尚未下载")')
lines.append('    if len(sys.argv) > 1:')
lines.append('        img = sys.argv[1]')
lines.append('        q = sys.argv[2] if len(sys.argv) > 2 else ""')
lines.append('        print()')
lines.append('        print("  分析图片:", img)')
lines.append('        print(handle_image(img, q))')
lines.append('')
lines.append('if __name__ == "__main__":')
lines.append('    main()')
